### ISSUE TITLE
Allure не генерирует отчет

### ISSUE THREAD

**Issue by KAKOC92** [KAKOC92/PatternsTask1#1]
При выполнении команды `allureServe`  отчет не генерируется, в терминале непонятная ошибка

![image](https://github.com/KAKOC92/PatternsTask1/assets/148219178/0df7fc19-58e2-4cfd-b7bd-0b5e32c9e328)

**Comment by andrew-pahomov** [comment]
Добрый день 

Прошу описать со скринами шаги прогона автотестов и генерации отчетов. Для выполнения операций прошу использовать консольные команды.
